### ISSUE TITLE
请问PatchEmbed23D的具体内容

### ISSUE THREAD

**Issue by yanglei1111** [Davidczy/Uni4Eye_pp#1]
models_mymae23D.py中
from timm.models.vision_transformer import PatchEmbed, Block, PatchEmbed23D这一行的 PatchEmbed23D的内容可以补充一下吗

**Comment by Davidczy** [comment]
Thank you for your interest in my work. I have uploaded the implementation of PatchEmbed23D to the repository. You can make modifications based on your task.

**Comment by yanglei1111** [comment]
Thank you very much for providing the code related to PatchEmbed23D. Could you please provide more details about the `main_pretrain.py` code? I couldn't find that file in the project.Especially regarding the intensity decoder and edge decoder mentioned in the paper.
