### ISSUE TITLE
Inquiry About main_pretrain.py and Details on Intensity Decoder and Edge Decoder in the Paper

### ISSUE THREAD

**Issue by yanglei1111** [Davidczy/Uni4Eye_pp#2]
Could you please provide more details about the `main_pretrain.py` code? I couldn't find that file in the project.Especially regarding the intensity decoder and edge decoder (Lssl = λ1Li + λ2Le) mentioned in the paper.

**Comment by Davidczy** [comment]
Sorry, my code is currently undergoing journal expansion. It will take some time before the code is fully released. However， my code is based on [MAE](https://github.com/facebookresearch/mae), if you find some codes missing in my project, you can refer to the implementation. For the dual decoder, I just copy the structure of Decoder in MAE. The only difference is the reconstruction target for these two branches.
